title: Vitals Simulation
remote_theme: just-the-docs/just-the-docs
color_scheme: light
search_enabled: true

just_the_docs:
  collections:
    drone-controller:
      name: Drone Controller
      permalink: /drone-controller/
    drone-environment:
      name: Drone Environment
      permalink: /drone-environment/
    project-setup:
      name: Project Setup
      permalink: /project-setup/