title: Vitals Simulation
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs
color_scheme: light
search_enabled: true

just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_fold: true
      permalink: /:collection/:path/